---
title: "Single alele model"
author: "Paulo Izquierdo"
output: html_document
editor_options: 
chunk_output_type: console
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message = F, 
                      warning = F)
```


### Genotype
```{r Genotype}
remove(list = ls())
 set.seed(10) # seed for the random number generator
 p=0.5
 n=10000 
```


### Phenotype
```{r }
a1= 1000 # additivity
a2= 800
d1= 0 #dominance
d2= 800
mu= 5000 # pop mean
H2= 0.5 # heritability

X1=rbinom(n=n,size=2,p=p) # sampling genotypes under HWE
X2=rbinom(n=n,size=2,p=p) 
X3=rbinom(n=n,size=2,p=p) 

G=mu+ifelse(X1==2,a1,ifelse(X1==1,d1,-a1)) +
     ifelse(X2==2,a2,ifelse(X2==1,d2,-a2)) # marker effect

vG=var(G) # an esitmate of the genetic variance
vE=vG*(1-H2)/H2 # with this error variance we will have the desired 
E=rnorm(n=n,sd=sqrt(vE))
var(G)/var(G+E) # rought estimate of the locus-heritability  


```

### Phenotype

```{r }
Y=G+E
par(mfrow= c(2,2), mai = c(0.35, 0.35, 0.35, 0.35))
class(X1)

boxplot(Y~X1, main = "Allele 1")
boxplot(Y~X2, main = "Allele 2")
boxplot(Y~X3, main = "Allele 3")
hist(Y, breaks = 50, col="cornflowerblue", main = "Yield")
```



### Average effect of allele substitution 

```{r allele effect}
fmA1=lm(Y~X1) # fits a linear model on genotypes (additive effects)
Z1=1.0*(X1==1) # Create a variable for A1A2 genotype
fmAD1=lm(Y~X1+Z1) # fits a linear model on genotypes (dominant effects)

fmA1
fmAD1

fmA2=lm(Y~X2) # fits a linear model on genotypes (additive effects)
Z2=1.0*(X2==1) # Create a variable for A1A2 genotype
fmAD2=lm(Y~X2+Z2) # fits a linear model on genotypes (dominant effects)
fmA2
fmAD2


fmA3=lm(Y~X3) # fits a linear model on genotypes (additive effects)
Z3=1.0*(X3==1) # Create a variable for A1A2 genotype
fmAD3=lm(Y~X3+Z3) # fits a linear model on genotypes (dominant effects)
fmA3
fmAD3
```

###Expected Value per Group

```{r Expected Values}
muA1A1=fmAD1$coef[1] #(i.e., the intercept)
muA1A2=fmAD1$coef[1]+fmAD1$coef[2]+fmAD1$coef[3] # Heterocygous A1A2, E[Y|X=1]
muA2A2=fmAD1$coef[1]+2*fmAD1$coef[2] # Homocygous A2A2, E[X=2]

muB1B1=fmAD2$coef[1] 
muB1B2=fmAD2$coef[1]+fmAD2$coef[2]+fmAD2$coef[3] 
muB2B2=fmAD2$coef[1]+2*fmAD2$coef[2] 

muC1C1=fmAD3$coef[1] 
muC1C2=fmAD3$coef[1]+fmAD3$coef[2]+fmAD3$coef[3] 
muC2C2=fmAD3$coef[1]+2*fmAD3$coef[2] 

exp_values = matrix(c(muA1A1, muA1A2, muA2A2, muB1B1, muB1B2, muB2B2, 
                      muC1C1, muC1C2, muC2C2 ), ncol = 3, byrow = T)

colnames(exp_values) = c("aa", "Ab","AA")
row.names(exp_values) = c("Allele1","Allele2", "Allele3")

exp_values = as.table(exp_values)
exp_values
```


###Models

```{r Models}
fm0=lm(Y~1) 
summary(fm0) # Null = intercept

anova(fm0,fmAD1) # testing wether there is an association, either additive effect or dominance or both
anova(fm0,fmAD2)
anova(fm0,fmAD3)

anova(fm0,fmA1) # Testing wether there is a additive association
anova(fm0,fmA2)
anova(fm0,fmA3)

anova(fmA1,fmAD1) # Testing whether there is dominance
anova(fmA2,fmAD2)
anova(fmA3,fmAD3)
```
